name: AllClaimPlotCommand
version: 1.0.0
api: 3.0.0
main: supercrafter333\AllClaimPlotCommand\AllClaimPlotCommand
author: supercrafter333
depend:
  - MyPlot

commands:
  allclaimplot:
    description: Give every player automatically a plot!
    aliases:
      - acp
    permission: "allclaimplotcommand.allclaimplot.cmd"

permissions:
  allclaimplot.admin:
    description: All permissions for the Plugin
    default: op
    children:
      allclaimplotcommand.allclaimplot.cmd:
        description: Command permission
        default: op
